server:
  port: 8085
spring:
  application:
    name: notification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3310/notification_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:eduflow}
    password: ${SPRING_DATASOURCE_PASSWORD:eduflow123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
api:
  key: ${API_KEY:NOTIFICATION-SERVICE-KEY-2024}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
